# Generated by Django 3.2.12 on 2024-10-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='url',
        ),
    ]
