# Generated by Django 3.2.5 on 2021-10-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('localisation', models.CharField(default='Antananarivo', max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='uploads/profile_pictures/profile.png', upload_to='uploads/profile_pictures')),
                ('fonction', models.BooleanField(blank=True, default=False)),
                ('contact', models.IntegerField(blank=True, default='034')),
                ('cin', models.CharField(blank=True, default='', max_length=50)),
                ('activities', models.CharField(blank=True, max_length=200, null=True)),
                ('nif', models.CharField(blank=True, default='', max_length=50)),
                ('stat', models.CharField(blank=True, default='', max_length=50)),
                ('lien', models.CharField(blank=True, default='', max_length=450)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserprofileFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450, verbose_name='title')),
                ('image', models.ManyToManyField(blank=True, to='Profile.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
