# Generated by Django 3.1.6 on 2021-08-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('localisation', models.CharField(default='Antananarivo', max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='uploads/profile_pictures/profile.png', upload_to='uploads/profile_pictures')),
                ('fonction', models.BooleanField(blank=True, default=False)),
                ('contact', models.IntegerField(blank=True, default='034')),
                ('cin', models.CharField(blank=True, default='', max_length=50)),
                ('activities', models.CharField(blank=True, max_length=200, null=True)),
                ('nif', models.CharField(blank=True, default='', max_length=50)),
                ('stat', models.CharField(blank=True, default='', max_length=50)),
                ('lien', models.CharField(blank=True, default='', max_length=450)),
            ],
        ),
    ]
