# Generated by Django 3.1.6 on 2011-01-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evenement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='tarif',
            field=models.CharField(default='0', max_length=250, verbose_name='tarif'),
        ),
    ]
