# Generated by Django 3.2.12 on 2024-10-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Evenement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='url',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='location',
            field=models.CharField(default='', max_length=250, verbose_name='location'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evenement.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
