# Generated by Django 3.2.12 on 2024-10-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evenement', '0002_auto_20241027_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Evenement.evenement'),
        ),
        migrations.AlterField(
            model_name='like',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Evenement.evenement'),
        ),
    ]
